###############################################
# service-ga / application.yml
#  Perfiles:
#    - ga   : Sede A  (Oracle localhost:1521/FREE)
#    - ga-b : Sede B  (Oracle localhost:1522/FREE)
###############################################

spring:
  application:
    name: service-ga

---
#########################################################
# PERFIL: SEDE A  (ga)
#########################################################
spring:
  config:
    activate:
      on-profile: ga

  datasource:
    url: jdbc:oracle:thin:@//localhost:1521/FREE
    username: biblio
    password: Biblio123
    driver-class-name: oracle.jdbc.OracleDriver

    hikari:
      maximum-pool-size: 12
      minimum-idle: 2
      idle-timeout: 30000
      max-lifetime: 600000
      connection-timeout: 10000

  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.OracleDialect
        format_sql: true
    show-sql: false

  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true

ga:
  sede: A

  local:
    path: "/tmp/biblio/sedeA"

  server:
    rep:
      port: 9020                   # REP para Actores→GA en sede A
      server: 0.0.0.0

   # Config de réplica: SOLO la sede A replica hacia la sede B
  replica:
    enabled: true
    # URL base HTTP del GA de la sede B (ajusta host/puerto según tu despliegue)
    # Ejemplo si GA-B corre en 8083 en la misma máquina:
    # base-url: "http://localhost:8083"
    base-url: "http://10.43.102.101:8082"          # <- RELLENAR con la URL de GA-B
    poll-interval-ms: 2000


management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus

server:
  port: 8081 
  address: 0.0.0.0  

---
#########################################################
# PERFIL: SEDE B  (ga-b)
#########################################################
spring:
  config:
    activate:
      on-profile: ga-b

  datasource:
    url: jdbc:oracle:thin:@//0.0.0.0:1521/FREE
    username: biblio
    password: Biblio123
    driver-class-name: oracle.jdbc.OracleDriver

    hikari:
      maximum-pool-size: 12
      minimum-idle: 2
      idle-timeout: 30000
      max-lifetime: 600000
      connection-timeout: 10000

  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.OracleDialect
        format_sql: true
    show-sql: false

  flyway:
    enabled: false
    # locations: classpath:db/migration
    # baseline-on-migrate: true

ga:
  sede: B

  local:
    path: "/tmp/biblio/sedeB"

  server:
    rep:
      port: 9030                   # puerto REP para Actores→GA en sede B
      server: 0.0.0.0

  # Sede B NO replica
  replica:
    enabled: false
    base-url: ""
    poll-interval-ms: 2000

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus

server:
  port: 8082
  address: 0.0.0.0